name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.7'
        channel: 'stable'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk --debug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: dental-case-app-debug
        path: build/app/outputs/flutter-apk/app-debug.apk
        
    - name: Build Release APK
      run: flutter build apk --release
      
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: dental-case-app-release
        path: build/app/outputs/flutter-apk/app-release.apk
        
    - name: Build Web (if possible)
      run: |
        # Try to build web version, but don't fail if it doesn't work
        flutter build web || echo "Web build failed (expected due to QR scanner)"
        
    - name: Upload Web Build
      uses: actions/upload-artifact@v4
      with:
        name: dental-case-app-web
        path: build/web/
      if: success() || failure() # Upload even if web build failed 