name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.7'
        channel: 'stable'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build Debug APK
      run: flutter build apk --debug
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: dental-case-app-debug
        path: build/app/outputs/flutter-apk/app-debug.apk 