name: Manual Build APK

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.7'
        channel: 'stable'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Get dependencies
      run: flutter pub get
      
    - name: Clean build
      run: flutter clean
      
    - name: Build APK
      run: flutter build apk --${{ github.event.inputs.build_type }} --verbose
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: dental-case-app-${{ github.event.inputs.build_type }}
        path: build/app/outputs/flutter-apk/app-${{ github.event.inputs.build_type }}.apk 